# Generated by Django 3.0 on 2025-07-07 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_auto_20250704_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
                ('text_complaint', models.TextField(verbose_name='Текст жалобы:')),
                ('apartments', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user_compainted',
                    to='property.Flat',
                    verbose_name='Квартира на которую жаловались:',
                    )),
                ('user', models.ForeignKey(                     
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='complaints_apartament',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Кто жаловался:',
                    )),
            ],
        ),
    ]
