# Generated by Django 5.2.4 on 2025-07-08 11:43

from django.db import migrations

import phonenumbers


def convert_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        phone_number = flat.owners_phonenumber
        if not phone_number:
            continue
 
        try:
            parsed_number = phonenumbers.parse(phone_number, "RU")
        except Exception as e:
            print(f'Ошибка: {e}')
            
            is_valid_number = phonenumbers.is_valid_number(parsed_number)
            if not is_valid_number:
                continue

            formated_number = phonenumbers.format_number(
                parsed_number,
                phonenumbers.PhoneNumberFormat.E164
            )
            flat.owner_pure_phone = formated_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(convert_phone_numbers)
    ]
