# Generated by Django 3.0 on 2025-07-09 10:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20250708_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('owner_name', models.CharField(
                    max_length=200, 
                    verbose_name='ФИО владельца:')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(
                    blank=True,
                    max_length=128,
                    region='RU',
                    verbose_name='Нормализованный номер владельца:')),
                ('owners_phonenumber', models.CharField(
                    max_length=20,
                    verbose_name='Номер владельца:')),
                ('flats', models.ManyToManyField(
                    related_name='flat_owners',
                    to='property.Flat',
                    verbose_name='Квартиры в собственности:')),
            ],
        ),
    ]
