# Generated by Django 3.0 on 2025-07-09 21:27

from django.db import migrations


def transfer_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber,
        )
        owner.flats.set([flat])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250709_1707'),
    ]

    operations = [
            migrations.RunPython(transfer_flats)
    ]
