# Generated by Django 3.0 on 2025-07-11 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0012_auto_20250710_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='apartments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_apartament', to='property.Flat', verbose_name='Квартира на которую жаловались:'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_compainted', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался:'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='flat_owners', to='property.Flat', verbose_name='Квартиры в собственности:'),
        ),
    ]
