# Generated by Django 3.0 on 2025-07-22 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0013_auto_20250711_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='apartments',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='apartaments',
                to='property.Flat',
                verbose_name='Квартира на которую жаловались:'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='complaints',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Кто жаловался:'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(
                db_index=True,
                related_name='owners',
                to='property.Flat',
                verbose_name='Квартиры в собственности:'),
        ),
    ]
